backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "album"
    label: "Album"
    folder: "/src/data/albums"
    create: true
    fields:
      - { name: "title", label: "Title" }
      - { name: "height", label: "Height" }
      - { name: "url", label: "EmbedURL" }
      - { name: "host", label: "Host" }
      - { name: "href", label: "href" }
